// Code generated by nixmod2go. DO NOT EDIT.
package main

import (
	"encoding/json"
)

type Either interface {
	isEither()
}

func (e EitherInt) isEither() {
}
func (e EitherStr) isEither() {
}

// EitherInt is a possible type for [Either].
type EitherInt int

// EitherStr is a possible type for [Either].
type EitherStr string

type Enum string

const (
	EnumA Enum = "a"
	EnumB Enum = "b"
	EnumC Enum = "c"
)

type NullableSubmodule struct {
	Enable bool `json:"enable"`
}

type Numbers struct {
	Between  int         `json:"between"`
	Float    float64     `json:"float"`
	Int      int         `json:"int"`
	Number   json.Number `json:"number"`
	Positive uint        `json:"positive"`
	S16      int16       `json:"s16"`
	S32      int32       `json:"s32"`
	S8       int8        `json:"s8"`
	U16      uint16      `json:"u16"`
	U32      uint32      `json:"u32"`
	U8       uint8       `json:"u8"`
	Unsigned uint        `json:"unsigned"`
}

type OneOf interface {
	isOneOf()
}

func (o OneOfInt) isOneOf() {
}
func (o OneOfStr) isOneOf() {
}
func (o OneOfBool) isOneOf() {
}
func (o OneOfAttrs) isOneOf() {
}

// OneOfInt is a possible type for [OneOf].
type OneOfInt int

// OneOfStr is a possible type for [OneOf].
type OneOfStr string

// OneOfBool is a possible type for [OneOf].
type OneOfBool bool

// OneOfAttrs is a possible type for [OneOf].
type OneOfAttrs map[string]any

type Submodule struct {
	InnerNullable *string `json:"innerNullable"`
	InnerString   string  `json:"innerString"`
}

type SubmoduleList struct {
	Enable bool `json:"enable"`
}

type SubmoduleSelfRef struct {
	CurrentName string `json:"currentName"`
}

type ExampleModule struct {
	Enable            bool               `json:"enable"`
	Anything          any                `json:"anything"`
	Attrs             map[string]any     `json:"attrs"`
	Bool              bool               `json:"bool"`
	Either            Either             `json:"either"`
	Enum              Enum               `json:"enum"`
	Internal          bool               `json:"internal"`
	Lines             string             `json:"lines"`
	Nullable          *string            `json:"nullable"`
	NullableSubmodule *NullableSubmodule `json:"nullableSubmodule"`
	Number            int                `json:"number"`
	Numbers           Numbers            `json:"numbers"`
	OneOf             OneOf              `json:"oneOf"`
	Path              string             `json:"path"`
	Port              uint16             `json:"port"`
	String            string             `json:"string"`
	StringAttrs       map[string]string  `json:"stringAttrs"`
	StringList        []string           `json:"stringList"`
	Submodule         Submodule          `json:"submodule"`
	SubmoduleList     []SubmoduleList    `json:"submoduleList"`
	SubmoduleSelfRef  SubmoduleSelfRef   `json:"submoduleSelfRef"`
	Uniq              string             `json:"uniq"`
}
